/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Înregistrare utilizator nou */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Username-ul utilizatorului */
                        username: string;
                        /**
                         * Format: email
                         * @description Email-ul utilizatorului
                         */
                        email: string;
                        /** @description Parola (min 6 caractere, cel puțin o literă mică, mare și o cifră) */
                        password: string;
                        /** @description Prenumele utilizatorului */
                        firstName: string;
                        /** @description Numele utilizatorului */
                        lastName: string;
                    };
                };
            };
            responses: {
                /** @description Utilizator înregistrat cu succes */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /** @example {
                         *       "success": true,
                         *       "message": "Utilizator înregistrat cu succes",
                         *       "data": {
                         *         "user": {
                         *           "_id": "507f1f77bcf86cd799439011",
                         *           "username": "john_doe",
                         *           "email": "john@example.com",
                         *           "firstName": "John",
                         *           "lastName": "Doe",
                         *           "isActive": true,
                         *           "createdAt": "2023-01-01T00:00:00.000Z"
                         *         },
                         *         "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                         *       }
                         *     } */
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Date invalide */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentificare utilizator */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @description Email-ul utilizatorului
                         */
                        email: string;
                        /** @description Parola utilizatorului */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Autentificare reușită */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /** @example {
                         *       "success": true,
                         *       "message": "Autentificare reușită",
                         *       "data": {
                         *         "user": {
                         *           "_id": "507f1f77bcf86cd799439011",
                         *           "username": "john_doe",
                         *           "email": "john@example.com",
                         *           "firstName": "John",
                         *           "lastName": "Doe",
                         *           "isActive": true,
                         *           "lastLogin": "2023-01-01T00:00:00.000Z"
                         *         },
                         *         "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                         *       }
                         *     } */
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Credențiale invalide */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deconectare utilizator */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deconectare reușită */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Token invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obține profilul utilizatorului curent */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profilul utilizatorului */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /** @example {
                         *       "success": true,
                         *       "data": {
                         *         "user": {
                         *           "_id": "507f1f77bcf86cd799439011",
                         *           "username": "john_doe",
                         *           "email": "john@example.com",
                         *           "firstName": "John",
                         *           "lastName": "Doe",
                         *           "isActive": true,
                         *           "lastLogin": "2023-01-01T00:00:00.000Z",
                         *           "createdAt": "2023-01-01T00:00:00.000Z"
                         *         }
                         *       }
                         *     } */
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Token invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /** Actualizează profilul utilizatorului */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Prenumele utilizatorului */
                        firstName?: string;
                        /** @description Numele utilizatorului */
                        lastName?: string;
                        /**
                         * Format: email
                         * @description Email-ul utilizatorului
                         */
                        email?: string;
                    };
                };
            };
            responses: {
                /** @description Profil actualizat cu succes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Date invalide */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Schimbă parola utilizatorului */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Parola curentă */
                        currentPassword: string;
                        /** @description Parola nouă (min 6 caractere, cel puțin o literă mică, mare și o cifră) */
                        newPassword: string;
                    };
                };
            };
            responses: {
                /** @description Parolă schimbată cu succes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Parolă curentă incorectă sau parolă nouă invalidă */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obține toate todo-urile utilizatorului cu filtrare */
        get: {
            parameters: {
                query?: {
                    /** @description Filtrare după status */
                    status?: "pending" | "in_progress" | "completed" | "cancelled";
                    /** @description Filtrare după prioritate */
                    priority?: "low" | "medium" | "high" | "urgent";
                    /** @description Filtrare după dată (azi, săptămâna aceasta, 2 săptămâni, luna aceasta, întârziat) */
                    dateFilter?: "today" | "week" | "two_weeks" | "month" | "overdue";
                    /** @description Căutare în titlu și descriere */
                    search?: string;
                    /** @description Numărul paginii */
                    page?: number;
                    /** @description Numărul de elemente per pagină */
                    limit?: number;
                    /** @description Câmpul de sortare */
                    sortBy?: "title" | "priority" | "dueDate" | "status" | "createdAt" | "updatedAt";
                    /** @description Ordinea de sortare */
                    sortOrder?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de todo-uri */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /** @example {
                         *       "success": true,
                         *       "data": {
                         *         "todos": [
                         *           {
                         *             "_id": "507f1f77bcf86cd799439011",
                         *             "title": "Cumpără pâine",
                         *             "description": "Nu uita să cumpăr pâine",
                         *             "status": "pending",
                         *             "priority": "medium",
                         *             "dueDate": "2023-12-31T23:59:59.000Z",
                         *             "isOverdue": false,
                         *             "timeUntilDue": "2 zile",
                         *             "progress": 0,
                         *             "user": {
                         *               "_id": "507f1f77bcf86cd799439012",
                         *               "firstName": "John",
                         *               "lastName": "Doe",
                         *               "username": "john_doe"
                         *             }
                         *           }
                         *         ],
                         *         "pagination": {
                         *           "currentPage": 1,
                         *           "totalPages": 1,
                         *           "totalItems": 1,
                         *           "itemsPerPage": 10
                         *         }
                         *       }
                         *     } */
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Token invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Creează un todo nou */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Titlul todo-ului */
                        title: string;
                        /** @description Descrierea todo-ului */
                        description?: string;
                        /**
                         * @description Prioritatea todo-ului
                         * @default medium
                         * @enum {string}
                         */
                        priority?: "low" | "medium" | "high" | "urgent";
                        /**
                         * Format: date-time
                         * @description Data de scadență
                         */
                        dueDate?: string;
                        /** @description Tag-urile asociate todo-ului */
                        tags?: string[];
                        /**
                         * @description Dacă todo-ul este public
                         * @default false
                         */
                        isPublic?: boolean;
                    };
                };
            };
            responses: {
                /** @description Todo creat cu succes */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /** @example {
                         *       "success": true,
                         *       "message": "Todo creat cu succes",
                         *       "data": {
                         *         "todo": {
                         *           "_id": "507f1f77bcf86cd799439011",
                         *           "title": "Cumpără pâine",
                         *           "description": "Nu uita să cumpăr pâine de la magazin",
                         *           "status": "pending",
                         *           "priority": "medium",
                         *           "dueDate": "2023-12-31T23:59:59.000Z",
                         *           "tags": [
                         *             "cumpărături",
                         *             "alimente"
                         *           ],
                         *           "isPublic": false,
                         *           "user": "507f1f77bcf86cd799439012",
                         *           "createdAt": "2023-01-01T00:00:00.000Z"
                         *         }
                         *       }
                         *     } */
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Date invalide */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obține statistici pentru todo-uri */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statisticile todo-urilor */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /** @example {
                         *       "success": true,
                         *       "data": {
                         *         "stats": {
                         *           "total": 10,
                         *           "completed": 5,
                         *           "pending": 3,
                         *           "inProgress": 1,
                         *           "cancelled": 1,
                         *           "overdue": 2,
                         *           "completionRate": 50,
                         *           "priorityBreakdown": {
                         *             "low": 2,
                         *             "medium": 4,
                         *             "high": 3,
                         *             "urgent": 1
                         *           }
                         *         }
                         *       }
                         *     } */
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Token invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obține un todo specific */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID-ul todo-ului */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Todo-ul găsit */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Token invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Todo nu a fost găsit */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /** Actualizează un todo */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID-ul todo-ului */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Titlul todo-ului */
                        title?: string;
                        /** @description Descrierea todo-ului */
                        description?: string;
                        /**
                         * @description Statusul todo-ului
                         * @enum {string}
                         */
                        status?: "pending" | "in_progress" | "completed" | "cancelled";
                        /**
                         * @description Prioritatea todo-ului
                         * @enum {string}
                         */
                        priority?: "low" | "medium" | "high" | "urgent";
                        /**
                         * Format: date-time
                         * @description Data de scadență
                         */
                        dueDate?: string;
                        /** @description Tag-urile asociate todo-ului */
                        tags?: string[];
                        /** @description Dacă todo-ul este public */
                        isPublic?: boolean;
                    };
                };
            };
            responses: {
                /** @description Todo actualizat cu succes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Date invalide */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Todo nu a fost găsit */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /** Șterge un todo */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID-ul todo-ului */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Todo șters cu succes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Token invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Todo nu a fost găsit */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Marchează todo ca completat */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID-ul todo-ului */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Todo marcat ca completat */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Token invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Todo nu a fost găsit */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/todos/{id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Marchează todo ca în progres */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID-ul todo-ului */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Todo marcat ca în progres */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Token invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Todo nu a fost găsit */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/todos/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Anulează todo */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID-ul todo-ului */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Todo anulat */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Token invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Todo nu a fost găsit */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** @description ID-ul unic al utilizatorului */
            _id?: string;
            /** @description Username-ul utilizatorului */
            username?: string;
            /**
             * Format: email
             * @description Email-ul utilizatorului
             */
            email?: string;
            /** @description Prenumele utilizatorului */
            firstName?: string;
            /** @description Numele utilizatorului */
            lastName?: string;
            /** @description Statusul contului */
            isActive?: boolean;
            /**
             * Format: date-time
             * @description Ultima conectare
             */
            lastLogin?: string;
            /**
             * Format: date-time
             * @description Data creării contului
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Data ultimei actualizări
             */
            updatedAt?: string;
        };
        Todo: {
            /** @description ID-ul unic al todo-ului */
            _id?: string;
            /** @description Titlul todo-ului */
            title?: string;
            /** @description Descrierea todo-ului */
            description?: string;
            /**
             * @description Statusul todo-ului
             * @enum {string}
             */
            status?: "pending" | "in_progress" | "completed" | "cancelled";
            /**
             * @description Prioritatea todo-ului
             * @enum {string}
             */
            priority?: "low" | "medium" | "high" | "urgent";
            /**
             * Format: date-time
             * @description Data de scadență
             */
            dueDate?: string;
            /**
             * Format: date-time
             * @description Data completării
             */
            completedAt?: string;
            /** @description Tag-urile asociate todo-ului */
            tags?: string[];
            /** @description Utilizatorul care a creat todo-ul */
            user?: components["schemas"]["User"];
            /** @description Dacă todo-ul este public */
            isPublic?: boolean;
            /** @description Dacă todo-ul este întârziat */
            isOverdue?: boolean;
            /** @description Timpul rămas până la scadență */
            timeUntilDue?: string;
            /** @description Progresul todo-ului (0-100) */
            progress?: number;
            /**
             * Format: date-time
             * @description Data creării
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Data ultimei actualizări
             */
            updatedAt?: string;
        };
        Error: {
            /** @example false */
            success?: boolean;
            /** @description Mesajul de eroare */
            message?: string;
            errors?: {
                /** @description Câmpul cu eroare */
                field?: string;
                /** @description Mesajul de eroare pentru câmp */
                message?: string;
                /** @description Valoarea care a cauzat eroarea */
                value?: string;
            }[];
        };
        Success: {
            /** @example true */
            success?: boolean;
            /** @description Mesajul de succes */
            message?: string;
            /** @description Datele returnate */
            data?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaUser = components['schemas']['User'];
export type SchemaTodo = components['schemas']['Todo'];
export type SchemaError = components['schemas']['Error'];
export type SchemaSuccess = components['schemas']['Success'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
