name: TodoList Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cod
        uses: actions/checkout@v4

      - name: Instalare Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalare dependențe
        run: npm install

      - name: Verificare ESLint
        run: npm run lint

      - name: Build aplicație
        run: npm run build
